name: BinderDocker
description: 'Creates a docker image of your repository to view the collection of notebooks'
inputs:
  docker-username:
    description: Docker registry username.
    required: false
    default: ${{ github.repository_owner }}
  docker-password:
    description: Docker registry password.
    required: false
    default: ${{ github.token }}
  docker-registry:
    description: Domain name of the docker registry.
    required: false
    default: ghcr.io
  image-name:
    description: |
      Name of the image, i.e., `NAMESPACE/IMAGE_NAME`.
      If not supplied, this defaults to `$DOCKER_USERNAME/$GITHUB_REPOSITORY_NAME`
      or `$GITHUB_REPOSITORY`.
    required: false
  image-tags:
    description: |
      Tag(s) of the image.
      Multiple tags must be separated by spaces.
    required: true
    default: latest
  image-user:
    description: username of the primary user in the image
    required: true
    default: jovyan
  image-dir:
    description: path inside the image where contents of the repositories are copied to
    required: false
  git-path:
    description: Path to the git repository to build. Defaults to current working directory.
    default: ""
    required: false
  git-ref:
    description: Git ref (e.g., commit hash) to assign to the 'repo2docker.ref' image label.
    required: true
    default: ${{ github.sha }}
  cache-image-names:
    description: |
      Names of previous versions of this image to use as cache.
      Multiple names must be separated by spaces.
    required: false
    default: ""
  cache-image-tags:
    description: |
      Tags of previous versions of this image to use as cache.
      Multiple tags must be separated by spaces.
    required: false
    default: ""
  repo2docker-args:
    description: Extra commandline arguments to be passed to repo2docker
    required: false
  repo2docker-version:
    description: Force a specific version of repo2docker to be installed. Either in the form of `repo2docker==<version>` for install from pypi, or `git+https://<github-url>@<commit-hash` for installing from a github repo / branch
    required: false
  dockerfile-append:
    description: |
      Appendix of Dockerfile commands to run at the end of the build.
      Can be used to customize the resulting image after all standard build steps finish.
    required: false
  test-script:
    description: |
      A bash script to run inside the container to test the built image.
      Example:
      ```
      python3 -m pip install --no-cache -r image-tests/requirements.txt
      pytest image-tests/
      ```
    required: false
  push:
    description: |
      Whether to push the image to the registry.
      Accepted values are 'true', 'True', '1', 'false', 'False', '0'.
    required: false
    default: 'false'
  check-public:
    description: |
      Validate that the image pushed to the registry is publicly visible.
      Accepted values are 'true', 'True', '1', 'false', 'False', '0'.
    required: false
outputs:
  image-base-name:
    description: |
      Full base name used for all images,
      i.e., the full image name minus the tag,
      e.g., 'ghcr.io/REPOSITORY_OWNER/REPOSITORY_NAME'
  image-names:
    description: Full names of all tagged docker images, as a JSON array string.
branding:
  color: 'gray-dark'
  icon: 'package'
runs:
  using: 'docker'
  image: 'Dockerfile'
